### ISSUE TITLE
Feat: hub 관련 기능 추가

### ISSUE THREAD

**Issue by ykchoi1203** [i-four-people/MSA-LogisticsHub#24]
## To-Do List

- [x] hub entity 추가 #25 
- [x] hub 관련 Create 기능 추가 #25 
- [x] hub 관련 Update, Delete 기능 추가 #26 
- [ ] hub 관련 검색 기능 추가
